### ISSUE TITLE
Building on macOS High Sierra

### ISSUE THREAD

**Issue by andrevenancio** [artoolkit/jsartoolkit5#85]
Following the instructions on how to build this, isn't sufficient.
Maybe would be nice if you guys could specify which versions of node / java / ecmscripten etc you have installed.

I've tried to install latest and also version 1.36.32-64bit and get the same error.

`[Andres-MacBook-Pro:jsartoolkit andrevenancio$ npm run build

> jsartoolkit@0.0.0 build /Users/andrevenancio/Downloads/jsartoolkit
> node tools/makem.js; echo Built at `date`

Running command: /Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/emcc -I/Users/andrevenancio/Downloads/artoolkit5-master/include -I/Users/andrevenancio/Downloads/jsartoolkit/build/ -I/Users/andrevenancio/Downloads/jsartoolkit/emscripten/ /Users/andrevenancio/Downloads/artoolkit5-master/lib/SRC/AR/arLabelingSub/*.c /Users/andrevenancio/Downloads/artoolkit5-master/lib/SRC/AR/*.c /Users/andrevenancio/Downloads/artoolkit5-master/lib/SRC/ARICP/*.c /Users/andrevenancio/Downloads/artoolkit5-master/lib/SRC/ARMulti/*.c /Users/andrevenancio/Downloads/artoolkit5-master/lib/SRC/Gl/gsub_lite.c -Oz  -Wno-warn-absolute-paths  -s TOTAL_MEMORY=268435456  -s NO_BROWSER=1  --memory-init-file 0  --bind    -o /Users/andrevenancio/Downloads/jsartoolkit/build/libar.bc 

stderr: INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/Users/andrevenancio/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.37.33, 1.37.32, 1.37.32)
ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:Assigning a non-existent settings attribute "NO_BROWSER"
WARNING:root: - perhaps a typo in emcc's  -s X=Y  notation?
WARNING:root: - (see src/settings.js for valid values)
ERROR: Linking globals named 'arglCameraFrustumRH': symbol multiply defined!
Traceback (most recent call last):
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/emcc", line 10, in <module>
    python_selector.run(__file__, profile=True)
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/python_selector.py", line 43, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/emcc.py", line 1459, in run
    shared.Building.link(linker_inputs, specified_target)
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/shared.py", line 1844, in link
    output = run_process([LLVM_LINK] + link_args + ['-o', target], stdout=PIPE).stdout
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/shared.py", line 131, in run_process
    return run_base(cmd, universal_newlines=universal_newlines, check=check, *args, **kw)
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/shared.py", line 127, in run_base
    result.check_returncode()
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/shared.py", line 114, in check_returncode
    raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
tools.shared.Py2CalledProcessError: Command '['/Users/andrevenancio/Downloads/emscriptenSDK/clang/e1.37.32_64bit/llvm-link', '/tmp/tmpNbi3SZ/arLabelingSubDBIC_0_75.o', '/tmp/tmpNbi3SZ/arLabelingSubDBRC_1_76.o', '/tmp/tmpNbi3SZ/arLabelingSubDBZ_2_77.o', '/tmp/tmpNbi3SZ/arLabelingSubDWIC_3_78.o', '/tmp/tmpNbi3SZ/arLabelingSubDWRC_4_79.o', '/tmp/tmpNbi3SZ/arLabelingSubDWZ_5_80.o', '/tmp/tmpNbi3SZ/arLabelingSubEBIC_6_81.o', '/tmp/tmpNbi3SZ/arLabelingSubEBRC_7_82.o', '/tmp/tmpNbi3SZ/arLabelingSubEBZ_8_83.o', '/tmp/tmpNbi3SZ/arLabelingSubEWIC_9_84.o', '/tmp/tmpNbi3SZ/arLabelingSubEWRC_10_85.o', '/tmp/tmpNbi3SZ/arLabelingSubEWZ_11_86.o', '/tmp/tmpNbi3SZ/ar3DCreateHandle_12_87.o', '/tmp/tmpNbi3SZ/ar3DUtil_13_88.o', '/tmp/tmpNbi3SZ/arCreateHandle_14_89.o', '/tmp/tmpNbi3SZ/arDetectMarker_15_90.o', '/tmp/tmpNbi3SZ/arDetectMarker2_16_91.o', '/tmp/tmpNbi3SZ/arFilterTransMat_17_92.o', '/tmp/tmpNbi3SZ/arGetLine_18_93.o', '/tmp/tmpNbi3SZ/arGetMarkerInfo_19_94.o', '/tmp/tmpNbi3SZ/arGetTransMat_20_95.o', '/tmp/tmpNbi3SZ/arGetTransMatStereo_21_96.o', '/tmp/tmpNbi3SZ/arImageProc_22_97.o', '/tmp/tmpNbi3SZ/arLabeling_23_98.o', '/tmp/tmpNbi3SZ/arPattAttach_24_99.o', '/tmp/tmpNbi3SZ/arPattCreateHandle_25_100.o', '/tmp/tmpNbi3SZ/arPattGetID_26_101.o', '/tmp/tmpNbi3SZ/arPattLoad_27_102.o', '/tmp/tmpNbi3SZ/arPattSave_28_103.o', '/tmp/tmpNbi3SZ/arUtil_29_104.o', '/tmp/tmpNbi3SZ/mAlloc_30_105.o', '/tmp/tmpNbi3SZ/mAllocDup_31_106.o', '/tmp/tmpNbi3SZ/mAllocInv_32_107.o', '/tmp/tmpNbi3SZ/mAllocMul_33_108.o', '/tmp/tmpNbi3SZ/mAllocTrans_34_109.o', '/tmp/tmpNbi3SZ/mAllocUnit_35_110.o', '/tmp/tmpNbi3SZ/mDet_36_111.o', '/tmp/tmpNbi3SZ/mDisp_37_112.o', '/tmp/tmpNbi3SZ/mDup_38_113.o', '/tmp/tmpNbi3SZ/mFree_39_114.o', '/tmp/tmpNbi3SZ/mInv_40_115.o', '/tmp/tmpNbi3SZ/mMul_41_116.o', '/tmp/tmpNbi3SZ/mPCA_42_117.o', '/tmp/tmpNbi3SZ/mSelfInv_43_118.o', '/tmp/tmpNbi3SZ/mTrans_44_119.o', '/tmp/tmpNbi3SZ/mUnit_45_120.o', '/tmp/tmpNbi3SZ/paramChangeSize_46_121.o', '/tmp/tmpNbi3SZ/paramClear_47_122.o', '/tmp/tmpNbi3SZ/paramDecomp_48_123.o', '/tmp/tmpNbi3SZ/paramDisp_49_124.o', '/tmp/tmpNbi3SZ/paramDistortion_50_125.o', '/tmp/tmpNbi3SZ/paramFile_51_126.o', '/tmp/tmpNbi3SZ/paramGL_52_127.o', '/tmp/tmpNbi3SZ/paramGetPerspective_53_128.o', '/tmp/tmpNbi3SZ/paramLT_54_129.o', '/tmp/tmpNbi3SZ/vAlloc_55_130.o', '/tmp/tmpNbi3SZ/vDisp_56_131.o', '/tmp/tmpNbi3SZ/vFree_57_132.o', '/tmp/tmpNbi3SZ/vHouse_58_133.o', '/tmp/tmpNbi3SZ/vInnerP_59_134.o', '/tmp/tmpNbi3SZ/vTridiag_60_135.o', '/tmp/tmpNbi3SZ/icpCalibStereo_61_136.o', '/tmp/tmpNbi3SZ/icpCore_62_137.o', '/tmp/tmpNbi3SZ/icpHandle_63_138.o', '/tmp/tmpNbi3SZ/icpPoint_64_139.o', '/tmp/tmpNbi3SZ/icpPointRobust_65_140.o', '/tmp/tmpNbi3SZ/icpStereoHandle_66_141.o', '/tmp/tmpNbi3SZ/icpStereoPoint_67_142.o', '/tmp/tmpNbi3SZ/icpStereoPointRobust_68_143.o', '/tmp/tmpNbi3SZ/icpUtil_69_144.o', '/tmp/tmpNbi3SZ/arMultiFreeConfig_70_145.o', '/tmp/tmpNbi3SZ/arMultiGetTransMat_71_146.o', '/tmp/tmpNbi3SZ/arMultiGetTransMatStereo_72_147.o', '/tmp/tmpNbi3SZ/arMultiReadConfigFile_73_148.o', '/tmp/tmpNbi3SZ/gsub_lite_74_149.o', '-o', '/Users/andrevenancio/Downloads/jsartoolkit/build/libar.bc']' returned non-zero exit status 1

exec error: Error: Command failed: /Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/emcc -I/Users/andrevenancio/Downloads/artoolkit5-master/include -I/Users/andrevenancio/Downloads/jsartoolkit/build/ -I/Users/andrevenancio/Downloads/jsartoolkit/emscripten/ /Users/andrevenancio/Downloads/artoolkit5-master/lib/SRC/AR/arLabelingSub/*.c /Users/andrevenancio/Downloads/artoolkit5-master/lib/SRC/AR/*.c /Users/andrevenancio/Downloads/artoolkit5-master/lib/SRC/ARICP/*.c /Users/andrevenancio/Downloads/artoolkit5-master/lib/SRC/ARMulti/*.c /Users/andrevenancio/Downloads/artoolkit5-master/lib/SRC/Gl/gsub_lite.c -Oz  -Wno-warn-absolute-paths  -s TOTAL_MEMORY=268435456  -s NO_BROWSER=1  --memory-init-file 0  --bind    -o /Users/andrevenancio/Downloads/jsartoolkit/build/libar.bc 
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/Users/andrevenancio/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.37.33, 1.37.32, 1.37.32)
ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:Assigning a non-existent settings attribute "NO_BROWSER"
WARNING:root: - perhaps a typo in emcc's  -s X=Y  notation?
WARNING:root: - (see src/settings.js for valid values)
ERROR: Linking globals named 'arglCameraFrustumRH': symbol multiply defined!
Traceback (most recent call last):
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/emcc", line 10, in <module>
    python_selector.run(__file__, profile=True)
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/python_selector.py", line 43, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/emcc.py", line 1459, in run
    shared.Building.link(linker_inputs, specified_target)
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/shared.py", line 1844, in link
    output = run_process([LLVM_LINK] + link_args + ['-o', target], stdout=PIPE).stdout
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/shared.py", line 131, in run_process
    return run_base(cmd, universal_newlines=universal_newlines, check=check, *args, **kw)
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/shared.py", line 127, in run_base
    result.check_returncode()
  File "/Users/andrevenancio/Downloads/emscriptenSDK/emscripten/1.37.33/tools/shared.py", line 114, in check_returncode
    raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
tools.shared.Py2CalledProcessError: Command '['/Users/andrevenancio/Downloads/emscriptenSDK/clang/e1.37.32_64bit/llvm-link', '/tmp/tmpNbi3SZ/arLabelingSubDBIC_0_75.o', '/tmp/tmpNbi3SZ/arLabelingSubDBRC_1_76.o', '/tmp/tmpNbi3SZ/arLabelingSubDBZ_2_77.o', '/tmp/tmpNbi3SZ/arLabelingSubDWIC_3_78.o', '/tmp/tmpNbi3SZ/arLabelingSubDWRC_4_79.o', '/tmp/tmpNbi3SZ/arLabelingSubDWZ_5_80.o', '/tmp/tmpNbi3SZ/arLabelingSubEBIC_6_81.o', '/tmp/tmpNbi3SZ/arLabelingSubEBRC_7_82.o', '/tmp/tmpNbi3SZ/arLabelingSubEBZ_8_83.o', '/tmp/tmpNbi3SZ/arLabelingSubEWIC_9_84.o', '/tmp/tmpNbi3SZ/arLabelingSubEWRC_10_85.o', '/tmp/tmpNbi3SZ/arLabelingSubEWZ_11_86.o', '/tmp/tmpNbi3SZ/ar3DCreateHandle_12_87.o', '/tmp/tmpNbi3SZ/ar3DUtil_13_88.o', '/tmp/tmpNbi3SZ/arCreateHandle_14_89.o', '/tmp/tmpNbi3SZ/arDetectMarker_15_90.o', '/tmp/tmpNbi3SZ/arDetectMarker2_16_91.o', '/tmp/tmpNbi3SZ/arFilterTransMat_17_92.o', '/tmp/tmpNbi3SZ/arGetLine_18_93.o', '/tmp/tmpNbi3SZ/arGetMarkerInfo_19_94.o', '/tmp/tmpNbi3SZ/arGetTransMat_20_95.o', '/tmp/tmpNbi3SZ/arGetTransMatStereo_21_96.o', '/tmp/tmpNbi3SZ/arImageProc_22_97.o', '/tmp/tmpNbi3SZ/arLabeling_23_98.o', '/tmp/tmpNbi3SZ/arPattAttach_24_99.o', '/tmp/tmpNbi3SZ/arPattCreateHandle_25_100.o', '/tmp/tmpNbi3SZ/arPattGetID_26_101.o', '/tmp/tmpNbi3SZ/arPattLoad_27_102.o', '/tmp/tmpNbi3SZ/arPattSave_28_103.o', '/tmp/tmpNbi3SZ/arUtil_29_104.o', '/tmp/tmpNbi3SZ/mAlloc_30_105.o', '/tmp/tmpNbi3SZ/mAllocDup_31_106.o', '/tmp/tmpNbi3SZ/mAllocInv_32_107.o', '/tmp/tmpNbi3SZ/mAllocMul_33_108.o', '/tmp/tmpNbi3SZ/mAllocTrans_34_109.o', '/tmp/tmpNbi3SZ/mAllocUnit_35_110.o', '/tmp/tmpNbi3SZ/mDet_36_111.o', '/tmp/tmpNbi3SZ/mDisp_37_112.o', '/tmp/tmpNbi3SZ/mDup_38_113.o', '/tmp/tmpNbi3SZ/mFree_39_114.o', '/tmp/tmpNbi3SZ/mInv_40_115.o', '/tmp/tmpNbi3SZ/mMul_41_116.o', '/tmp/tmpNbi3SZ/mPCA_42_117.o', '/tmp/tmpNbi3SZ/mSelfInv_43_118.o', '/tmp/tmpNbi3SZ/mTrans_44_119.o', '/tmp/tmpNbi3SZ/mUnit_45_120.o', '/tmp/tmpNbi3SZ/paramChangeSize_46_121.o', '/tmp/tmpNbi3SZ/paramClear_47_122.o', '/tmp/tmpNbi3SZ/paramDecomp_48_123.o', '/tmp/tmpNbi3SZ/paramDisp_49_124.o', '/tmp/tmpNbi3SZ/paramDistortion_50_125.o', '/tmp/tmpNbi3SZ/paramFile_51_126.o', '/tmp/tmpNbi3SZ/paramGL_52_127.o', '/tmp/tmpNbi3SZ/paramGetPerspective_53_128.o', '/tmp/tmpNbi3SZ/paramLT_54_129.o', '/tmp/tmpNbi3SZ/vAlloc_55_130.o', '/tmp/tmpNbi3SZ/vDisp_56_131.o', '/tmp/tmpNbi3SZ/vFree_57_132.o', '/tmp/tmpNbi3SZ/vHouse_58_133.o', '/tmp/tmpNbi3SZ/vInnerP_59_134.o', '/tmp/tmpNbi3SZ/vTridiag_60_135.o', '/tmp/tmpNbi3SZ/icpCalibStereo_61_136.o', '/tmp/tmpNbi3SZ/icpCore_62_137.o', '/tmp/tmpNbi3SZ/icpHandle_63_138.o', '/tmp/tmpNbi3SZ/icpPoint_64_139.o', '/tmp/tmpNbi3SZ/icpPointRobust_65_140.o', '/tmp/tmpNbi3SZ/icpStereoHandle_66_141.o', '/tmp/tmpNbi3SZ/icpStereoPoint_67_142.o', '/tmp/tmpNbi3SZ/icpStereoPointRobust_68_143.o', '/tmp/tmpNbi3SZ/icpUtil_69_144.o', '/tmp/tmpNbi3SZ/arMultiFreeConfig_70_145.o', '/tmp/tmpNbi3SZ/arMultiGetTransMat_71_146.o', '/tmp/tmpNbi3SZ/arMultiGetTransMatStereo_72_147.o', '/tmp/tmpNbi3SZ/arMultiReadConfigFile_73_148.o', '/tmp/tmpNbi3SZ/gsub_lite_74_149.o', '-o', '/Users/andrevenancio/Downloads/jsartoolkit/build/libar.bc']' returned non-zero exit status 1

Built at Fri 9 Feb 2018 12:46:17 GMT`

**Comment by ThorstenBux** [comment]
I'm using this:
```
Zaphod:jekyll-pug-material-master thorstenbux$ emcc -v
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/Users/thorstenbux/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
INFO:root:(Emscripten: Running sanity checks)
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.22
clang version 4.0.0  (emscripten 1.37.22 : 1.37.22)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Users/thorstenbux/build-tools/emsdk-portable/clang/e1.37.22_64bit
INFO:root:(Emscripten: Running sanity checks)
```

And it works nicely. Please head over to artoolkitX https://github.com/artoolkitx/jsartoolkit5 I'm sure it builds from there.

You could also use Docker to build. See instructions on artoolkitX repo

**Comment by andrevenancio** [comment]
Will give that a try. thanks @ThorstenBux btw, are you aware of progress on `nft` branch? or any idea on how the legacy examples using markers are way slower on that branch? (Just asking since I saw you commit recently, assuming you're building it?)
thanks

**Comment by ThorstenBux** [comment]
@andrevenancio I haven't done much on the NFT branch. As far as I know it works but very slow on mobile which is why I didn't merge it. 
On which branch is the marker tracking slower? Couldn't quite get that from your question.

Cheers

**Comment by andrevenancio** [comment]
Hey, so If I pull the build minified version from the `nft` branch, and just try to run any of the examples on the `main` branch but with that (nft minified) version, the simple examples with the hiro and kenji markers are performing poorly and there's a warning saying `Performance warning: KPM processing is not using a mono pixel format.`. I was trying to build this in the first place to try to understand if I could fix this warning and hopefully get the simple examples back to standard performance speed, but I couldn't even build it. And to add to your comment, the NFT examples not only run slow on mobile, but they run slow on desktop. I get 20FPS on my laptop running https://rawgit.com/artoolkit/jsartoolkit5/nft/examples/nft_threejs.html and also on that branch https://rawgit.com/artoolkit/jsartoolkit5/nft/examples/pattern_threejs.html runs at 39-41fps compared to 60FPS of the https://rawgit.com/artoolkit/jsartoolkit5/examples/pattern_threejs.html example
